export const mapping = {
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  zip: "application/zip",
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  mp4: "video/mp4",
  rar: "application/x-rar-compressed",
  json: "application/json",
  svg: "image/svg+xml",
  png: "image/png",
  csv: "text/csv",
  ppt: "pplication/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  html: "text/html",
  txt: "text/plain",
  apk: "application/vnd.android.package-archive",
  exe: "application/octet-stream",
  mp3: "audio/mpeg",
  tar: "application/x-tar",
  jar: "application/java-archive",
};
